import struct
import sys

# The below script is generated by Gemini.

def verify_itch(filename):
    add_count = 0
    with open(filename, "rb") as f:
        while add_count < 10:   # modify to check the first N add orders
            # Read the 2-byte length prefix
            len_bytes = f.read(2)
            if not len_bytes: break
            msg_len = struct.unpack(">H", len_bytes)[0]
            
            # Read the exact message payload
            payload = f.read(msg_len)
            msg_type = chr(payload[0])
            
            if msg_type == 'A':
                # ITCH 5.0 Add Order Format (> means Big-Endian):
                # c: Msg Type (1) | H: Locate (2) | H: Tracking (2) | 6s: Timestamp (6) 
                # Q: Order ID (8) | c: Side (1)   | I: Shares (4)   | 8s: Stock (8) | I: Price (4)
                # Total = 36 bytes
                unpacked = struct.unpack(">cHH6sQcI8sI", payload)
                
                order_id = unpacked[4]
                side = unpacked[5].decode('ascii')
                shares = unpacked[6]
                stock = unpacked[7].decode('ascii')
                price = unpacked[8]
                
                print(f"[PY]  Add Order -> ID: {order_id} | Stock: '{stock}' | Shares: {shares} | Price: {price}")
                add_count += 1

if __name__ == "__main__":
    verify_itch("./files/01302019.NASDAQ_ITCH50")